import Utils from "../helper/utils";

const commonConstants = {
//   days: 30,
  limit: 100,
//   guestMiles: 5,
  saltRound: 10,
//   maxDistance: 5,
//   deleteCounts: 3,
//   masterOTP: 8569,
//   groupLimit: 100,
//   searchLimit: 20,
//   countryLimit: 5,
//   searchLength: 3,
//   homeFeedLimit: 5,
//   morning: [8, 10],
//   nearCityLimit: 6,
//   popularLimit: 10,
//   userListLimit: 5,
//   dishShowLimit: 6,
//   nearBusiDist: 50,
//   evening: [18, 20],
//   homeFeedMiles: 50,
//   nearBusiLimit: 20,
//   postTimeLimit: 30,
//   oneMile: 1609.344,
//   dishSearchLimit: 9,
//   busiSearchLimit: 5,
//   passwordAttempt: 3,
//   userText: " users",
//   afternoon: [12, 14],
//   thumbImageSize: 400,
//   googleTimeout: 5000,
//   activeUsersLimit: 50,
//   maxBusiDistance: 100,
//   guestToken: 'is-guest',
//   searchSectionLimit: 50,
//   teamName: 'Grubshoots',
//   imageType: 'image/png',
//   dateFormat: 'DD-MM-YYYY',
  authToken: 'x-auth-token',
//   businessId: 'business-id',
//   hoursFormat: ['AM', 'PM'],
  timezone: "Europe/London",
//   tmpImagePath: 'tmpimage/',
//   googleType: ['restaurant'],
//   milesArray: [1, 10, 30, 50],
//   dishImagePath: 'dishimage/',
//   postImagePath: 'postimage/',
//   branchIOMessage: 'Grubshoots',
//   thumbImagePath: 'thumbimage/',
//   verifyType: ['email', 'phone'],
//   showList: ['users', 'country'],
//   replaceAgoWith: 'a minute ago',
//   replaceAgo: 'a few seconds ago',
//   userProfilePath: 'userprofile/',
//   commentSort: ['recent', 'like'],
//   unsetLocation: ['Set Location'],
//   tabList: ['restaurant', 'admin'],
//   feedType: ['public', 'following'],
//   businessImagePath: 'businessimage/',
//   originalImagePath: 'originalimage/',
//   requestStatus: ['accept', 'reject'],
//   viewNotify: " viewed your profile.",
//   notifyCountType: ['post', 'business'],
//   overallSearch: ['history', 'popular'],
//   dietsMealsImagePath: 'dietsmealsimage/',
//   countryWiseList: ['users', 'restaurant'],
//   differenceDateFormat: 'YYYY-MM-DD HH:mm:ss',
//   teamMemberProfilePath: 'teammemberprofile/',
//   sorting: ['alphabetical', 'newest', 'highest'],
//   googlePhotoUrl: 'https://lh3.googleusercontent.com',
//   filters: ['all', 'today', 'week', 'monthly', 'custom'],
//   milesCheck: [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144],
//   userStatus: ['followers', 'following', 'viewed', 'blocked'],
//   businessInfoType: ["Images", "Basic Profile", "Opening Hours"],
//   bucketUrl: 'https://dev-grubshoots.s3.eu-west-2.amazonaws.com/',
//   termsUrl: 'https://www.iubenda.com/terms-and-conditions/71630770',
//   privacyPolicyUrl: 'https://www.iubenda.com/privacy-policy/71630770',
//   guestUrl: ['/home-feed', '/feed', '/popular-location', '/post-detail'],
//   logoUrl: 'https://dev-grubshoots.s3.eu-west-2.amazonaws.com/grub_shoots.png',
//   weekDay: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
//   backgroundUrl: ['/near-business', '/contact-sync-notifications', '/notifications-setting', '/verified'],
//   feedViewType: ['trendingFood', 'activeUsers', 'spotCuisines', 'dietConscious', 'popularMeals', 'nearCities', 'topRankedRests'],
//   passUrl: ['/resend-otp', '/get-profile', '/user-profile', '/verify-otp', '/change-password', '/change-phone-number', '/edit-profile', '/set-location', '/popular-location', '/location-history', '/resend-verification', '/near-contacts', '/near-fb-users', '/nearby-friends', '/search-history', '/overall-search', '/search-username', '/status-list', '/home-feed', '/feed', '/post-detail', '/logout', '/follow-unfollow'],
};

export default commonConstants;
